// JS FK against the reference (kinematics/test_vectors.json, generated by kinematics.py) on the same URDFs.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fk, tip, sample, limitViolations } from '../src/robot/kinematics.js';

const root = new URL('../../../kinematics/', import.meta.url);
const vectors = JSON.parse(readFileSync(new URL('test_vectors.json', root)));
const chains = JSON.parse(readFileSync(new URL('./fixtures_chains.json', import.meta.url)));   // written by the Python test from the URDFs

for (const name of Object.keys(vectors)) {
  test(`FK matches the reference on ${vectors[name].length} ${name} vectors`, () => {
    let worst = 0;
    for (const v of vectors[name]) { const p = tip(chains[name], v.angles); worst = Math.max(worst, Math.hypot(p[0] - v.expected_ee[0], p[1] - v.expected_ee[1], p[2] - v.expected_ee[2])); }
    assert.ok(worst < 1e-9, `worst ${worst}`);
  });
  test(`limit check agrees with the reference flags on ${name}`, () => {
    for (const v of vectors[name]) assert.equal(limitViolations(chains[name], [v.angles]).length > 0, v.is_violation);
  });
}

test('points include every joint origin and the tip', () => {
  const r = fk(chains.planar_3_dof, [0, 0, 0]);
  assert.deepEqual(r.points.map(p => p.map(x => Math.round(x * 1e9) / 1e9)), [[0, 0, 0], [0, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0]]);
});

test('trajectory sampling interpolates and clamps', () => {
  const tr = { t: [0, 1, 3], q: [[0, 0], [1, 2], [3, 2]], pen: [0, 1, 1] };
  assert.deepEqual(sample(tr, -1).q, [0, 0]);
  assert.deepEqual(sample(tr, 2).q, [2, 2]);
  assert.equal(sample(tr, 2).pen, 1); assert.equal(sample(tr, 0.5).pen, 0);
  assert.deepEqual(sample(tr, 9).q, [3, 2]);
});
