# -*- coding: utf-8 -*-
"""Promotion path (SPEC N-04): agent-written generator code -> sandbox -> conformance kit (G-05) -> artist approval
-> versioned plugin in the artist's private plugin dir. Promoted plugins STILL run inside the sandbox: their code is
never imported into the studio process.

    P = sandboxed_plugin(source, name)          # a PLUGIN dict whose four functions each run in the sandbox
    r = check(source, name, worlds)             # {"ok", "rows", "reason"}  (conformance on the reference worlds)
    install(source, name, version, rows, root)  # only called by the approval executor (A-06)

The source defines translate(axes), generate(world, intent, params), self_assess(world, artifact), ports(world, params)
with the same meaning as engine/plugins/*/plugin.py, using only the standard library.
"""
from __future__ import annotations

import hashlib
import json
import re
import time
from pathlib import Path

from worldengine import conformance as CF, sandbox as SB
from worldengine.studio import config

_HARNESS = '''
import json
__inp = json.load(open("input.json"))
__fn = {"translate": lambda a: translate(*a), "generate": lambda a: generate(*a), "self_assess": lambda a: self_assess(*a), "ports": lambda a: ports(*a)}
print(json.dumps({"out": __fn[__inp["fn"]](__inp["args"])}))
'''


class SandboxError(RuntimeError):
    pass


def _safe_name(name: str) -> str:
    if not re.fullmatch(r"[a-z][a-z0-9_]{1,40}", name or ""):
        raise ValueError("plugin name must be lowercase letters, digits, _ (2-41 chars)")
    return name


def sandboxed_plugin(source: str, name: str, version: str = "0", medium: str = "image") -> dict:
    def call(fn, *args):
        r = SB.run(source + "\n" + _HARNESS, inputs={"fn": fn, "args": list(args)})
        if not r.get("ran"):
            raise SandboxError(r.get("reason"))
        if not (isinstance(r.get("result"), dict) and "out" in r["result"]):
            raise SandboxError("%s failed (exit %s, %s): %s" % (fn, r.get("exit"), r.get("killed"), r.get("stderr", "")[-300:]))
        return r["result"]["out"]
    return {"name": _safe_name(name), "version": version, "medium": medium, "sandboxed": True,
            "translate": lambda axes: call("translate", axes), "generate": lambda w, i, p: call("generate", w, i, p),
            "self_assess": lambda w, a: call("self_assess", w, a), "ports": lambda w, p: call("ports", w, p)}


def check(source: str, name: str, worlds) -> dict:
    ok, why = SB.available()
    if not ok:
        return {"ok": False, "rows": [], "reason": "샌드박스를 만들 수 없어 실행하지 않았다: " + why}
    rows = CF.run(sandboxed_plugin(source, name), list(worlds))
    bad = [r for r in rows if not r["ok"]]
    return {"ok": bool(rows) and not bad, "rows": rows, "reason": "" if not bad else "적합성 실패: " + "; ".join("%s %s %s" % (r["world"], r["clause"], r["detail"]) for r in bad[:4])}


def plugin_root(root=None) -> Path:
    return Path(root or config.data_dir()) / "plugins"


def install(source: str, name: str, version: str, rows, root=None) -> dict:
    """The approval executor calls this. Writes a wrapper that runs the source in the sandbox on every call."""
    d = plugin_root(root) / _safe_name(name)
    d.mkdir(parents=True, exist_ok=True)
    (d / "source.py").write_text(source, encoding="utf-8")
    (d / "meta.json").write_text(json.dumps({"name": name, "version": version, "sha256": hashlib.sha256(source.encode()).hexdigest(),
                                             "approved_at": time.time(), "conformance": [{k: r[k] for k in ("world", "clause", "ok")} for r in rows]},
                                            ensure_ascii=False, indent=1), encoding="utf-8")
    (d / "plugin.py").write_text(
        "# generated by worldengine.promote -- runs source.py in the sandbox on every call\n"
        "from pathlib import Path\nimport json\nfrom worldengine import promote\n"
        "_d = Path(__file__).parent\n_m = json.loads((_d / 'meta.json').read_text(encoding='utf-8'))\n"
        "PLUGIN = promote.sandboxed_plugin((_d / 'source.py').read_text(encoding='utf-8'), _m['name'], _m['version'])\n", encoding="utf-8")
    return {"installed": str(d), "version": version}
